### ISSUE TITLE
Application UI Sheet links don’t close the sheet

### ISSUE THREAD

**Issue by iamhectorsosa** [iamhectorsosa/supabase-modules#16]
There is a component that renders the application UI with a side sheet. This is using a Radix dialog, please make sure that clicking the links in the side sheet closes the dialog

**Comment by rudokotrla** [comment]
Could you please provide exact steps to reproduce 🙏  @iamhectorsosa ? (feel free to use the new template for bug reports). I am having trouble reproducing this.

**Comment by iamhectorsosa** [comment]
This issue has been addressed with recent commits restructuring routes.
