### ISSUE TITLE
bug: unable to create a bookmark

### ISSUE THREAD

**Issue by rudokotrla** [iamhectorsosa/supabase-modules#21]
### What happened?

After submitting an url there is the error:

> Something went wrong!
> Bookmark creation was not successful, please try again; ref: 3635507823

### Steps to reproduce

1. Go to bookmarks
2. Paste some valid url to the input
3. Hit save
4. There is an error message, no bookmark added

### What browsers are you seeing the problem on?

Chrome

### Additional context

Happens in dev localhost. Docker with DB running. From what I inspected, the error seems to be with DB, all the data are correctly passed to the:

```
supabase
    .from("bookmarks")
    .insert(...)
```

Cannot see DB logs in the Supabase Studio for some reason, though.

**Comment by iamhectorsosa** [comment]
Cannot check local environment at the time being but production seems to be working fine. Can you confirm if you are experiencing the same issue in the production environment?

**Comment by rudokotrla** [comment]
It works fine in production and it also works in localhost now. Not sure what the problem was before. This can be closed now.
