### ISSUE TITLE
bug: Profile settings - link to Account settings not working

### ISSUE THREAD

**Issue by rudokotrla** [iamhectorsosa/supabase-modules#22]
### What happened?

The link to Account settings not working from within the Profile settings.

### Steps to reproduce

1. Go to Profile settings
2. Click on Account settings next to the "Update Settings" button
3. It redirects to wrong link and thus shows 404

### What browsers are you seeing the problem on?

Chrome

**Comment by iamhectorsosa** [comment]
This is correct. The URL links to /settings/account and it should be linked to /settings/accounts

However I would just remove these from profile and credentials as I don't believe it makes much sense to have those when we can access those locations using other navigation components.
