### ISSUE TITLE
feat: Add Anonymous User Access

### ISSUE THREAD

**Issue by iamhectorsosa** [iamhectorsosa/supabase-modules#32]
### Reason for feature

Users should be able to interact with the application without having to sign in.

### Proposed solution

Enable a button that says "Continue as Guest" to enable anonymous sign ins.

### Alternatives / Available workarounds

N/A

### Additional context

Docs: https://supabase.com/docs/guides/auth/auth-anonymous

**Comment by rudokotrla** [comment]
I managed to enable the anonymous sign-in and make necessary DB trigger changes to support this.  We still need to decide what do we want the user experience for the anonymous user to be. In particular:
- which views are accessible to anonymous users
  - enable RLS according to this
- provide way(s) to convert to permanent user
  - provide conflict resolution in case user does sth as guest and then decides to log in (the case when he has an account) 

My idea is to keep the bookmarks section enabled as it is also for anonymous users. Regarding the settings page in the case user is anonymous, we shouldn't show any settings (profile, credentials, account) at this point but rather the information that to view this section registration process needs to be finished and provide link to the "finish sign up" form. 

Other possible issue with anonymous users is [possible abuse](https://supabase.com/docs/guides/auth/auth-anonymous#abuse-prevention-and-rate-limits) so proper rate limiting and/or adding a captcha check. Do we want to include them in the project somehow?

Also, signing in anonymous users creates rows in the `auth.users` table the same way as for permanent users but we probably don't want to keep these entries forever. Therefore, there is a need for a mechanism that would clean up these entries in the `auth.users` table. Currently this [not supported by Supabase directly](https://supabase.com/docs/guides/auth/auth-anonymous#automatic-cleanup) (and PostgreSQL does not have time-based triggers) but this can be attained by using job scheduler, for example: https://supabase.com/docs/guides/database/extensions/pg_cron.

I am very welcome to any suggestions.
