### ISSUE TITLE
Email change has to trigger an update on the user's profile once confirmed

### ISSUE THREAD

**Issue by iamhectorsosa** [iamhectorsosa/supabase-modules#8]
When a user changes their email, it needs to be confirmed, but once the email change is confirmed we should update the profiles with the new email. There might be several ways to do this, we need to evaluate which one is the best. Might even do a trigger function at the database level.

**Comment by rudokotrla** [comment]
As I am trying out the flow I am thinking I should probably show some message after email update submission that email was sent to the new address and it needs to be confirmed. Wdyt @iamhectorsosa ?

**Comment by iamhectorsosa** [comment]
Absolutely! This would be great feedback. Cause changing email is a bit of an unclear process.

We need to inform the user the following:
1. This needs to be confirmed before going into effect
2. User needs to check and confirm in BOTH of their emails, the current and new email since we send two emails for this action
3. Once both of the emails are confirmed, changes will go into effect.

Of course we have to come with good wording for this, but those are the main points. Maybe an alert dialog would be the best option here. With a disclaimer title and message about this action. Open to suggestions.
